### ISSUE TITLE
Hoping to use this in current cohort of datasci capstone

### ISSUE THREAD

**Issue by stichbury** [stichbury/dsci-benchmark#1]
Hi there @hfoffani & @jan-san
I found your benchmark code (by accident) and it looks really useful. I wonder if you'd mind if I use it and - if so - please could you share the password for the zip file. I'll obviously keep it secure and will put any changes I make to the code back up for others to use.

I hope that's OK with you.  Many thanks in advance!
Jo

**Comment by hfoffani** [comment]
Hi,
Thanks for your words. It's been a long time since I worked with this project and I will need a couple of days to update myself. What I do remember is that original zip file contained the answers of the quizzes (as a way to compare the algorithm with ourselves).
Let me research this a bit and I'll come back again soon.
Hernán.

**Comment by jan-san** [comment]
Hi stichbury,

I still have the source files from the zip, but I'm hesitant to give them out because as Hernán wrote already they contain the solution of the Capstone quizzes, so sharing the file could be considered a violation of the Coursera terms.
Similarly, sharing tweets obtained via the twitter API would be a violation of their license.

However, you can re-create both the blogs and the tweets data set using the script generate_dataset.R - the quizzes dataset can simply be recreated by pasting the quiz sentences into a text file one sentence per line.

Jan

**Comment by stichbury** [comment]
Hi @hfoffani & @jan-san

Thanks for getting back to me - I appreciate it. I can see why you'd be cautious, and although I've completed the quizzes, I understand that you need to avoid violating their terms.  I'll use your scripts directly and see how I get on.

Thanks again! 
Jo
